# Generated by Django 5.0.4 on 2024-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_pics',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
