# Generated by Django 5.0.4 on 2024-04-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_person_profile_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.TextField(default=' ', verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name="Person's first name"),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=30, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_pics',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='Profile Pics'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=80)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.person')),
            ],
        ),
    ]
