# Generated by Django 5.0.4 on 2024-04-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_person_email_alter_person_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
