# Generated by Django 5.0.4 on 2024-04-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_person_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
